coding_task:
  description: >
    Write python code to achieve this: {assignment}
  expected_output: >
    A text file includes the code itself, along with the ourput of the code.
  agent: coder
  output_file: output/code_and_output.txt
